# Random Forest Tree:
 is a `supervised learning algorithm`. Like you can already see from it's name, it create a `forest` and makes it somehow random. The `'forest'` it builds, is an `ensemble of Decision Tree`, most of the time trained with the `'begging'` method. The general idea of the `bagging method` is that a combination of learning models increases the overall result.

 To say it in simple words: `Random Forest` builds multiple decision tree and merges them together to get a more accurate and stable prediction.

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [29]:
df= sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [30]:
# encode feature which are categorical or object using for lop
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype== 'object' or df[col].dtype == 'category':
        df[col] = le.fit_transform(df[col])
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [31]:
# split the data X and y and classification:
X = df.drop('sex', axis= 1)
y = df['sex']

In [32]:
# train test split the model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20, random_state=42)

In [36]:
# create, train, predict the model
model =RandomForestClassifier(n_estimators=200,criterion= 'gini', random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Evaluate the model
print('accuracy_score:', accuracy_score(y_test, y_pred))
print('confusion_matrix: \n', confusion_matrix(y_test, y_pred))
print('classification report \n:', classification_report(y_test, y_pred))

accuracy_score: 0.6122448979591837
confusion_matrix:
 [[ 7 12]
 [ 7 23]]
classification report
:               precision    recall  f1-score   support

           0       0.50      0.37      0.42        19
           1       0.66      0.77      0.71        30

    accuracy                           0.61        49
   macro avg       0.58      0.57      0.57        49
weighted avg       0.60      0.61      0.60        49

# Random Forest using regressor:

In [44]:
X =df.drop('tip', axis= 1)
y = df['tip']

# train test split the model
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.20, random_state=42)

# create, train, predict the model
model =RandomForestRegressor( n_estimators=200 , random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

# Evaluate the model
print('mean_absolute_error:', mean_absolute_error(y_test, y_pred))
print('mean_squared_error:', mean_squared_error(y_test, y_pred))
print('r2_score:', r2_score(y_test, y_pred))
print('root mean squared error:', np.sqrt(y_test, y_pred))

mean_absolute_error: 0.7704663265306128
mean_squared_error: 0.9496955984183694
r2_score: 0.2402261043743361
root mean squared error: 24     1.783255
6      1.414214
153    1.414214
211    2.271563
198    1.414214
176    1.414214
192    1.600000
124    1.587451
9      1.797220
101    1.732051
45     1.732051
233    1.212436
117    1.224745
177    1.414214
82     1.352775
146    1.166190
200    2.000000
15     1.979899
66     1.571623
142    2.236068
33     1.565248
19     1.830301
109    2.000000
30     1.204159
186    1.870829
120    1.519868
10     1.307670
73     2.236068
159    1.414214
156    2.236068
112    2.000000
218    1.200000
25     1.529706
60     1.791647
18     1.870829
119    1.708801
97     1.224745
197    2.236068
139    1.658312
241    1.414214
75     1.118034
127    1.414214
113    1.596872
16     1.292285
196    1.414214
67     1.000000
168    1.268858
38     1.519868
195    1.200000
Name: tip, dtype: float64